### ISSUE TITLE
How to run the code on own dataset?

### ISSUE THREAD

**Issue by rockywind** [ai4ce/Occ4cast#1]
Hi, thank you for sharing the great work.
I am interseted in running the code to generate 4D occupancy grid on my own dataset.
The format of my dataset is similar to that of the Nuscene dataset,containing lidar data, multi-view images and IMU data.
I would appreciate any assistance or guidance on how to preoceed.

**Comment by Gaaaavin** [comment]
Thank you for your interest in our work.

In your case, I think the best approach is to modify our data processing code for your dataset. You can modify the processing code for the Lyft dataset in `data_processing/lyft`, as the Lyft dataset has a very similar structure to the nuScenes dataset.

After the data processing, you can use/modify the dataloader for Lyft to run different baselines on your dataset.

**Comment by rockywind** [comment]
thanks a lot.

**Comment by simbaforrest** [comment]
@Gaaaavin maybe you should add this instruction to the readme.md

**Comment by rockywind** [comment]
Hi, I have two questions.
1. Can I genera the 4D occupancy grid data using only the 3D box label, lidar data, multi-view images and IMU data?
2. Are the instance label and bounding boxes 2D?

**Comment by Gaaaavin** [comment]
1. The current ground-truth generation pipeline requires the pose data for each frame. It is important for point cloud aggregation and dynamic object synchronization. Though you can do registration or integration from the data you provided, the accuracy is not guaranteed.
2. We used the 3D labels and bounding boxes.
