### ISSUE TITLE
argoverse_v1.1 dataset for SSCBench

### ISSUE THREAD

**Issue by yyash-patel** [ai4ce/Occ4cast#2]
Hello ,

I wanted to know if the argoverse-v1.1 dataset can be used for SSCBench after preprocessing it using the steps mentioned in the [link](https://github.com/ai4ce/Occ4cast/tree/main/data_processing/argoverse).

Thanks,
Yash

**Comment by Gaaaavin** [comment]
The data processing code in the link is for Occ4cast.
Note that Argoverse does not provide semantic labels for point clouds, hence can't be used for SSCBench.

**Comment by yyash-patel** [comment]
understood, thank you !
