### ISSUE TITLE
How to visualize?

### ISSUE THREAD

**Issue by gfhdhy** [ai4ce/Occ4cast#3]
Hello!
The visualization code data_processing/visualization/visualize_voxels.py seems to be designed for semantic-kitti dataset.
What should I do exactly to visualize voxels in other datasets.
Thank you!

**Comment by Gaaaavin** [comment]
The data format of OCFBench generally follows semantic-kitti. For other datasets, you can convert the voxel file into the semantic-kitti format (bin file of XYZ array) and then run the visualization.
For converting the whole dataset, if your dataset shares a similar structure with one of our datasets, you can refer to our data processing code in the `data_processing` folder.

**Comment by rockywind** [comment]
Hi, thank you for sharing the great work.
I don't known how to generate the following visualization, can you sharing the visualization code?
![image](https://github.com/ai4ce/Occ4cast/assets/14838781/214ceddc-d617-48db-ae3f-b6489feaacb1)

**Comment by Gaaaavin** [comment]
You can use [`visualize_voxels.py`](https://github.com/ai4ce/Occ4cast/blob/2f32310367e90b453c356f3d9abed893c08cedcd/data_processing/visualization/visualize_voxels.py) for visualization.

Note that the corresponding config file assigns color by class labels. To replicate the visualization, you need to first process the voxels to give them pseudo-labels according to their z-axis values.
