### ISSUE TITLE
Error of convert_apollo

### ISSUE THREAD

**Issue by huanghh1519** [ai4ce/Occ4cast#4]
Hello,
I want to ask how to deal with the following error in convert_apollo.py when executing ./apolloscape/run_convert.sh:

(occ4cast) huanghh1519@huanghh1519:~/Repo/Occ4cast-main/data_processing/apolloscape$ /bin/bash /home/huanghh1519/Repo/Occ4cast-main/data_processing/apolloscape/run_convert.sh
Start converting dataset, scene: 8 - 9
Traceback (most recent call last):
  File "/home/huanghh1519/Repo/Occ4cast-main/data_processing/apolloscape/convert_apollo.py", line 164, in <module>
    trip_id, segment_id = id_mapping[i]
KeyError: 8
(occ4cast) huanghh1519@huanghh1519:~/Repo/Occ4cast-main/data_processing/apolloscape$ 

Thank you!

**Comment by Gaaaavin** [comment]
The processing code is for the detection/tracking dataset in ApolloScape. Please make sure the data is downloaded in correct format
