### ISSUE TITLE
For Waymo dataset

### ISSUE THREAD

**Issue by Zbozhou** [ai4ce/Occ4cast#6]
Appreciate for your excellent work, I am wondering when the Waymo Dataset will be released.

**Comment by Gaaaavin** [comment]
The dataset is almost ready. Please expect the release in a couple of weeks. Thank you for your patience.

**Comment by Gaaaavin** [comment]
Sorry for the very long delay.
OCFBench-Waymo is now available on Hugging Face: https://huggingface.co/datasets/ai4ce/OCFBench
