### ISSUE TITLE
    from cumm.inliner import NVRTCInlineBuilder ModuleNotFoundError: No module named 'cumm'

### ISSUE THREAD

**Issue by rockywind** [ai4ce/Occ4cast#7]
Hi, 
I met the error below when I run the script `ray_model`
Can you helip me?
````
Occ4cast-main/data_processing/raymodel/utils/ray_traversal.py", line 4, in <module>
    from cumm.inliner import NVRTCInlineBuilder
ModuleNotFoundError: No module named 'cumm'
````

**Comment by Gaaaavin** [comment]
Please follow [README](https://github.com/ai4ce/Occ4cast/blob/main/data_processing/nuscenes/README.md) to install the corresponding packages.
