### ISSUE TITLE
voxelize script

### ISSUE THREAD

**Issue by lzbushicai** [ai4ce/Occ4cast#9]
Hi, how did you handle the point cloud and labels, got the following file, I would like to do the same for my dataset, can you share your script please?

```
|   |   |   |-- voxels # voxelized point clouds
|   |   |   |   |-- 0000.bin # voxelized input
|   |   |   |   |-- 0000.label # voxelized label
|   |   |   |   |-- 0000.invalid # voxelized invalid mask
|   |   |   |   |-- 0001.bin
|   |   |   |   |-- 0001.label
|   |   |   |   |-- 0001.invalid
```

**Comment by Gaaaavin** [comment]
You can follow the script in the [data processing](https://github.com/ai4ce/Occ4cast/tree/main/data_processing) folder. The script is generally the same but has slight difference for different datasets.
